use anyhow::{Context, Result};
use reqwest::cookie::CookieStore;
use reqwest::header::HeaderValue;
use std::io::BufRead;
use std::sync::{Arc, Mutex};

/// Representa um cookie no formato Netscape.
#[derive(Debug, Clone)]
pub struct NetscapeCookie {
    pub domain: String,
    pub path: String,
    pub secure: bool,
    /// Unix epoch em segundos. 0 = cookie de sessão.
    pub expires: u64,
    pub name: String,
    pub value: String,
}

/// Carrega cookies de um arquivo no formato Netscape.
pub fn load_netscape_cookies(path: &str) -> Result<Vec<NetscapeCookie>> {
    let file = std::fs::File::open(path)
        .with_context(|| format!("Falha ao abrir arquivo de cookies: {}", path))?;
    let reader = std::io::BufReader::new(file);
    let mut cookies = Vec::new();

    for line in reader.lines() {
        let line = line?;
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = trimmed.split('\t').collect();
        if parts.len() != 7 {
            // Fallback: tenta separar por espaços (alguns arquivos usam espaços)
            let parts_space: Vec<&str> = trimmed.split_whitespace().collect();
            if parts_space.len() != 7 {
                continue;
            }
            cookies.push(parse_netscape_line(&parts_space)?);
        } else {
            cookies.push(parse_netscape_line(&parts)?);
        }
    }

    Ok(cookies)
}

fn parse_netscape_line(parts: &[&str]) -> Result<NetscapeCookie> {
    Ok(NetscapeCookie {
        domain: parts[0].to_string(),
        path: parts[2].to_string(),
        secure: parts[3].eq_ignore_ascii_case("TRUE"),
        expires: parts[4].parse().unwrap_or(0),
        name: parts[5].to_string(),
        value: parts[6].to_string(),
    })
}

/// Salva cookies em um arquivo no formato Netscape.
pub fn save_netscape_cookies(cookies: &[NetscapeCookie], path: &str) -> Result<()> {
    let mut file = std::fs::File::create(path)
        .with_context(|| format!("Falha ao criar arquivo de cookies: {}", path))?;

    use std::io::Write;
    writeln!(file, "# Netscape HTTP Cookie File")?;
    writeln!(
        file,
        "# This file was generated by faf-browser. Edit at your own risk."
    )?;

    for c in cookies {
        let flag = if c.domain.starts_with('.') {
            "TRUE"
        } else {
            "FALSE"
        };
        let secure = if c.secure { "TRUE" } else { "FALSE" };
        writeln!(
            file,
            "{}\t{}\t{}\t{}\t{}\t{}\t{}",
            c.domain, flag, c.path, secure, c.expires, c.name, c.value
        )?;
    }

    Ok(())
}

/// Faz o parse de um header Set-Cookie em um NetscapeCookie.
/// `default_domain` e `default_path` são usados quando não especificados no header.
pub fn parse_set_cookie(
    header: &str,
    default_domain: &str,
    default_path: &str,
) -> Option<NetscapeCookie> {
    let segments: Vec<&str> = header.split(';').collect();
    if segments.is_empty() {
        return None;
    }

    let first = segments[0].trim();
    let mut name_value = first.splitn(2, '=');
    let name = name_value.next()?.trim().to_string();
    let value = name_value.next().unwrap_or("").trim().to_string();

    let mut domain = default_domain.to_string();
    let mut path = default_path.to_string();
    let mut secure = false;
    let mut expires: u64 = 0;

    for seg in &segments[1..] {
        let seg = seg.trim();
        if seg.eq_ignore_ascii_case("Secure") {
            secure = true;
            continue;
        }
        if seg.eq_ignore_ascii_case("HttpOnly") || seg.eq_ignore_ascii_case("SameSite") {
            // Não armazenados no formato Netscape
            continue;
        }

        let mut kv = seg.splitn(2, '=');
        let key = kv.next()?.trim();
        let val = kv.next().unwrap_or("").trim();

        if key.eq_ignore_ascii_case("Domain") {
            domain = val.to_string();
            if !domain.starts_with('.') && domain.split('.').count() > 1 {
                domain = format!(".{}", domain);
            }
        } else if key.eq_ignore_ascii_case("Path") {
            path = val.to_string();
        } else if key.eq_ignore_ascii_case("Max-Age") {
            if let Ok(seconds) = val.parse::<i64>()
                && seconds > 0
            {
                let now = std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_secs();
                expires = now + seconds as u64;
            }
        } else if key.eq_ignore_ascii_case("Expires") {
            // Tenta RFC 2822
            if let Ok(dt) = time::OffsetDateTime::parse(
                val,
                &time::format_description::well_known::Rfc2822,
            ) {
                expires = dt.unix_timestamp().max(0) as u64;
            }
        }
    }

    Some(NetscapeCookie {
        domain,
        path,
        secure,
        expires,
        name,
        value,
    })
}

/// Constrói o valor do header Cookie a partir dos cookies que correspondem à URL.
pub fn build_cookie_header(cookies: &[NetscapeCookie], url: &url::Url) -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    let domain = url.host_str().unwrap_or("");
    let path = url.path();

    let matching: Vec<String> = cookies
        .iter()
        .filter(|c| {
            // Expirado?
            if c.expires > 0 && c.expires < now {
                return false;
            }
            // Match de domínio
            let d = &c.domain;
            if d == domain {
                return true;
            }
            if let Some(suffix) = d.strip_prefix('.')
                && (domain == suffix || domain.ends_with(d))
            {
                return true;
            }
            false
        })
        .filter(|c| path.starts_with(&c.path))
        .filter(|c| {
            if c.secure {
                url.scheme() == "https"
            } else {
                true
            }
        })
        .map(|c| format!("{}={}", c.name, c.value))
        .collect();

    matching.join("; ")
}

/// Mescla um cookie no jar, substituindo se já existir com mesmo domínio+name+path.
pub fn merge_cookie(jar: &mut Vec<NetscapeCookie>, cookie: NetscapeCookie) {
    if let Some(pos) = jar.iter().position(|c| {
        c.domain == cookie.domain && c.name == cookie.name && c.path == cookie.path
    }) {
        jar[pos] = cookie;
    } else {
        jar.push(cookie);
    }
}

// ---------------------------------------------------------------------------
// NetscapeCookieStore — wrapper que delega ao reqwest::cookie::Jar e
// mantém um mirror em Vec<NetscapeCookie> para persistência no formato
// Netscape (--cookies / --cookies-jar).
// ---------------------------------------------------------------------------

#[derive(Clone)]
pub struct NetscapeCookieStore {
    inner: Arc<reqwest::cookie::Jar>,
    netscape: Arc<Mutex<Vec<NetscapeCookie>>>,
}

impl Default for NetscapeCookieStore {
    fn default() -> Self {
        Self::new()
    }
}

impl NetscapeCookieStore {
    pub fn new() -> Self {
        Self {
            inner: Arc::new(reqwest::cookie::Jar::default()),
            netscape: Arc::new(Mutex::new(Vec::new())),
        }
    }

    /// Carrega cookies de um arquivo Netscape para o store.
    pub fn load_from_file(&self, path: &str) -> anyhow::Result<()> {
        let cookies = load_netscape_cookies(path)?;
        for cookie in &cookies {
            let mut set_cookie = format!(
                "{}={}; Domain={}; Path={}",
                cookie.name,
                cookie.value,
                cookie.domain.trim_start_matches('.'),
                cookie.path,
            );
            if cookie.secure {
                set_cookie.push_str("; Secure");
            }
            if cookie.expires > 0 {
                let dt = time::OffsetDateTime::from_unix_timestamp(cookie.expires as i64)
                    .unwrap_or(time::OffsetDateTime::UNIX_EPOCH);
                let expires_str = dt
                    .format(&time::format_description::well_known::Rfc2822)
                    .unwrap_or_default();
                if !expires_str.is_empty() {
                    set_cookie.push_str(&format!("; Expires={}", expires_str));
                }
            }

            let scheme = if cookie.secure { "https" } else { "http" };
            let host = cookie.domain.trim_start_matches('.');
            let url_str = format!("{}://{}{}", scheme, host, cookie.path);
            if let Ok(url) = reqwest::Url::parse(&url_str) {
                self.inner.add_cookie_str(&set_cookie, &url);
            }
        }
        *self.netscape.lock().unwrap() = cookies;
        Ok(())
    }

    /// Salva o mirror Netscape para arquivo.
    pub fn save_to_file(&self, path: &str) -> anyhow::Result<()> {
        let cookies = self.netscape.lock().unwrap();
        save_netscape_cookies(&cookies, path)?;
        Ok(())
    }
}

impl CookieStore for NetscapeCookieStore {
    fn set_cookies(
        &self,
        cookie_headers: &mut dyn Iterator<Item = &HeaderValue>,
        url: &reqwest::Url,
    ) {
        for header in cookie_headers {
            if let Ok(value) = header.to_str() {
                self.inner.add_cookie_str(value, url);
                let domain = url.host_str().unwrap_or("");
                let path = url.path();
                if let Some(cookie) = parse_set_cookie(value, domain, path) {
                    merge_cookie(&mut self.netscape.lock().unwrap(), cookie);
                }
            }
        }
    }

    fn cookies(&self, url: &reqwest::Url) -> Option<HeaderValue> {
        self.inner.cookies(url)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_netscape_line() {
        let line = vec![".example.com", "TRUE", "/", "FALSE", "1735689600", "sid", "abc123"];
        let c = parse_netscape_line(&line).unwrap();
        assert_eq!(c.domain, ".example.com");
        assert_eq!(c.path, "/");
        assert!(!c.secure);
        assert_eq!(c.expires, 1735689600);
        assert_eq!(c.name, "sid");
        assert_eq!(c.value, "abc123");
    }

    #[test]
    fn test_parse_set_cookie_simple() {
        let c = parse_set_cookie("session=xyz", "example.com", "/").unwrap();
        assert_eq!(c.name, "session");
        assert_eq!(c.value, "xyz");
        assert_eq!(c.domain, "example.com");
        assert_eq!(c.path, "/");
    }

    #[test]
    fn test_parse_set_cookie_with_attrs() {
        let c = parse_set_cookie(
            "id=42; Domain=example.com; Path=/api; Secure; Max-Age=3600",
            "example.com",
            "/",
        )
        .unwrap();
        assert_eq!(c.name, "id");
        assert_eq!(c.value, "42");
        assert_eq!(c.domain, ".example.com");
        assert_eq!(c.path, "/api");
        assert!(c.secure);
        assert!(c.expires > 0);
    }

    #[test]
    fn test_build_cookie_header() {
        let cookies = vec![
            NetscapeCookie {
                domain: ".example.com".to_string(),
                path: "/".to_string(),
                secure: false,
                expires: 0,
                name: "a".to_string(),
                value: "1".to_string(),
            },
            NetscapeCookie {
                domain: ".example.com".to_string(),
                path: "/api".to_string(),
                secure: true,
                expires: 0,
                name: "b".to_string(),
                value: "2".to_string(),
            },
        ];
        let url = url::Url::parse("https://example.com/api/test").unwrap();
        let header = build_cookie_header(&cookies, &url);
        assert!(header.contains("a=1"));
        assert!(header.contains("b=2"));
    }

    #[test]
    fn test_build_cookie_header_secure_filter() {
        let cookies = vec![NetscapeCookie {
            domain: ".example.com".to_string(),
            path: "/".to_string(),
            secure: true,
            expires: 0,
            name: "s".to_string(),
            value: "1".to_string(),
        }];
        let https_url = url::Url::parse("https://example.com/").unwrap();
        let http_url = url::Url::parse("http://example.com/").unwrap();
        assert_eq!(build_cookie_header(&cookies, &https_url), "s=1");
        assert_eq!(build_cookie_header(&cookies, &http_url), "");
    }

    #[test]
    fn test_merge_cookie() {
        let mut jar = vec![NetscapeCookie {
            domain: ".example.com".to_string(),
            path: "/".to_string(),
            secure: false,
            expires: 0,
            name: "x".to_string(),
            value: "old".to_string(),
        }];
        merge_cookie(
            &mut jar,
            NetscapeCookie {
                domain: ".example.com".to_string(),
                path: "/".to_string(),
                secure: false,
                expires: 0,
                name: "x".to_string(),
                value: "new".to_string(),
            },
        );
        assert_eq!(jar.len(), 1);
        assert_eq!(jar[0].value, "new");
    }
}
